// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STEMotion.Infrastructure.DBContext;

#nullable disable

namespace STEMotion.Infrastructure.Migrations
{
    [DbContext(typeof(StemotionContext))]
    [Migration("20260215062912_ThanhDT_ErikDev")]
    partial class ThanhDT_ErikDev
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STEMotion.Domain.Entities.Chapter", b =>
                {
                    b.Property<Guid>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chapter_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ChapterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("chapter_name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subject_id");

                    b.HasKey("ChapterId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Chapter", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ConfigData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("config_data");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("game_code");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("thumbnail_url");

                    b.HasKey("GameId");

                    b.HasIndex("GameCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Game_GameCode");

                    b.HasIndex("LessonId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.GameResult", b =>
                {
                    b.Property<Guid>("GameResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_result_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int")
                        .HasColumnName("correct_answers");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("game_id");

                    b.Property<int>("PlayDuration")
                        .HasColumnType("int")
                        .HasColumnName("play_duration");

                    b.Property<DateTime>("PlayedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("played_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int")
                        .HasColumnName("total_questions");

                    b.HasKey("GameResultId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayedAt")
                        .HasDatabaseName("IX_GameResult_PlayedAt");

                    b.HasIndex("StudentId", "GameId")
                        .HasDatabaseName("IX_GameResult_StudentId_GameId");

                    b.ToTable("GameResult", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Grade", b =>
                {
                    b.Property<Guid>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("GradeLevel")
                        .HasColumnType("int")
                        .HasColumnName("grade_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GradeId");

                    b.HasIndex("GradeLevel")
                        .IsUnique();

                    b.HasIndex("OrderIndex")
                        .HasDatabaseName("IX_Grade_OrderIndex");

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("chapter_id");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("int")
                        .HasColumnName("estimated_time");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lessonName");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("ChapterId");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.LessonContent", b =>
                {
                    b.Property<Guid>("LessonContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_content_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("FormulaLatex")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("formula_latex");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("media_url");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("TextContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text_content");

                    b.HasKey("LessonContentId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonContent", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("info");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("first_name");

                    b.Property<int?>("GradeLevel")
                        .HasColumnType("int")
                        .HasColumnName("grade_level");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("last_name");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parent_id");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("StudentId");

                    b.HasIndex("ParentId");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("IX_Student_Username")
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.StudentProgress", b =>
                {
                    b.Property<Guid>("StudentProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_progress_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompletionPercentage")
                        .HasColumnType("int")
                        .HasColumnName("completion_percentage");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_accessed_at");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("lesson_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("NotStarted")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StudentProgressId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.HasIndex("StudentId", "LessonId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentProgress_Student_Lesson");

                    b.ToTable("StudentProgress", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subject_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("grade_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SubjectId");

                    b.HasIndex("GradeId");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("billing_period");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("SubscriptionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("subscription_name");

                    b.Property<decimal>("SubscriptionPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subscription_price");

                    b.HasKey("SubscriptionId");

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.Property<Guid>("SubscriptionPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_payment_id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("account_number");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("CounterAccountBankId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("counter_account_bank_id");

                    b.Property<string>("CounterAccountName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("counter_account_name");

                    b.Property<string>("CounterAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("counter_account_number");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<long?>("OrderCode")
                        .HasColumnType("bigint")
                        .HasColumnName("order_code");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<string>("PaymentLinkId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("payment_link_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reference");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("subscription_id");

                    b.Property<bool?>("Success")
                        .HasColumnType("bit")
                        .HasColumnName("is_success");

                    b.Property<DateTime?>("TransactionDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_datetime");

                    b.HasKey("SubscriptionPaymentId");

                    b.HasIndex("PaymentId")
                        .IsUnique();

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SubscriptionPayment", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userId")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatarUrl");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("firstName");

                    b.Property<int?>("GradeLevel")
                        .HasColumnType("int")
                        .HasColumnName("gradeLevel");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("roleId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Subject", "Subject")
                        .WithMany("Chapters")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Chapter.subject_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Game", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Game.lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.GameResult", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Game", "Game")
                        .WithMany("GameResults")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GameResult.game_id");

                    b.HasOne("STEMotion.Domain.Entities.Student", "Student")
                        .WithMany("GameResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GameResult.student_id");

                    b.Navigation("Game");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Lessons")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Lesson.chapter_id");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.LessonContent", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Lesson", "Lesson")
                        .WithMany("LessonContents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LessonContent.lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Payment", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Payment_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Student", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.User", "Parent")
                        .WithMany("Students")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Student_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.StudentProgress", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Lesson", "Lesson")
                        .WithMany("StudentProgress")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudentProgress_lesson_id");

                    b.HasOne("STEMotion.Domain.Entities.Student", "Student")
                        .WithMany("StudentProgress")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudentProgress_student_id");

                    b.HasOne("STEMotion.Domain.Entities.User", null)
                        .WithMany("StudentProgress")
                        .HasForeignKey("UserId");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Subject", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Subject.grade_id");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.SubscriptionPayment", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Payment", "Payment")
                        .WithOne("SubscriptionPayment")
                        .HasForeignKey("STEMotion.Domain.Entities.SubscriptionPayment", "PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STEMotion.Domain.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionPayments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.User", b =>
                {
                    b.HasOne("STEMotion.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User.role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Game", b =>
                {
                    b.Navigation("GameResults");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("LessonContents");

                    b.Navigation("StudentProgress");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Payment", b =>
                {
                    b.Navigation("SubscriptionPayment")
                        .IsRequired();
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Student", b =>
                {
                    b.Navigation("GameResults");

                    b.Navigation("StudentProgress");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("SubscriptionPayments");
                });

            modelBuilder.Entity("STEMotion.Domain.Entities.User", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("StudentProgress");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
